### ISSUE TITLE
Can I make the title bar to dark?

### ISSUE THREAD

**Issue by milindgoel15** [maboroshin/qBittorrentDarktheme#19]
![500072600073_49358](https://user-images.githubusercontent.com/45682747/103150811-a9d9e880-479d-11eb-87da-66a2ae0d3ee7.jpg)
the white bar at the top. i am using iceberg theme

**Comment by maboroshin** [comment]
@milindgoel15 At the moment it can not be changed by the theme. It may be possible to change it by improving the program (qBitTorrent).

**Comment by milindgoel15** [comment]
So that depends on the app itself. I saw some screenshots in this repo for same theme and other themes but with different versions of app that they are using dark color instead of white.

Do you know a way to make it dark? Something in the settings I am missing?

**Comment by maboroshin** [comment]
@milindgoel15 Probably, there is an OS setting that dark to the title bar (probably Linux). I don't think it's a qBitTorrent setting.

**Comment by milindgoel15** [comment]
Ah f

**Comment by jagannatharjun** [comment]
you can do this via windows setting https://github.com/jagannatharjun/qbt-theme/issues/40#issuecomment-743693923

**Comment by despepas** [comment]
> ![500072600073_49358](https://user-images.githubusercontent.com/45682747/103150811-a9d9e880-479d-11eb-87da-66a2ae0d3ee7.jpg)
> the white bar at the top. i am using iceberg theme

Try this:

Prerequisites
How to get dark theme title bars in windows 10, without changing your accent colour - onmsft. Com - january 16, 2019
To achieve this effect, you'll first need to head to the "Settings" app. Open the "Personalisation" category and click to the "Colours" page. Make sure the "Title bars" checkbox is ticked under "Show the accent colour on the following surfaces" section. You should also make sure you've selected your desired accent colour – if you change it later, you will need to repeat this procedure to reinstate your black title bars.

Finding the registry node
Next, search for "regedit" in the Start menu and hit enter to launch it. At this point, it's time for our routine reminder – registry edits can have unforeseen consequences for your system and are not supported by Microsoft. This trick may break or stop working in the future and you use it at your own risk.

Navigate to the following key:

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM
If you have a recent build of Windows 10, you can copy and paste the key directly into the registry editor's address bar. Otherwise, you'll need to drill down through the registry nodes yourself using the tree view in the Registry Editor's left pane.

How to get dark theme title bars in windows 10, without changing your accent colour - onmsft. Com - january 16, 2019
Before we get editing, one word of warning: it's possible some of the keys mentioned in the next section don't yet exist on your system. If you can't see a mentioned key, create it by right-clicking the Registry Editor window and selecting "New", then "DWORD (32-bit value)". Name the key according to the instructions given below.

Black title bars with an accent colour
In the right pane, displaying the values in the registry node, double click the "ColorPrevalence" key to edit its value. Set it to "1" (without the quotes) and click OK.

How to get dark theme title bars in windows 10, without changing your accent colour - january 16, 2019
Next, double click the "AccentColor" key and change its value to "0d0d0d" – this is the hexadecimal colour code to use for the title bars. Unfortunately, extremely dark values appear to be rejected by Windows, so a simple "000000" for a full black doesn't work. You can try different colour codes to fine tune your results.

Finally, edit the "AccentColorInactive" key and set its value to your chosen colour code. This defines the title bar colour of apps which are inactive and in the background on your desktop. You're free to use a different shade here if you'd prefer to make inactive apps more visually distinct from the foreground app.

How to get dark theme title bars in windows 10, without changing your accent colour - onmsft. Com - january 16, 2019
That's all there is to it! The changes should apply immediately once you select or open windows on your desktop. You'll now have black title bars while preserving your regular accent colour used in the Start menu, Action Centre and other areas of the interface.

You can finetune the title bar effect to suit your taste using the AccentColor and AccentColorInactive registry keys. Just remember that if you change your system accent colour in settings, you may need to run through these steps again to restore your black title bars.

Sources: www.onmsft.com/how-to/how-to-get-dark-theme-title-bars-in-windows-10-without-changing-your-accent-colour

Edit 1:
This is an example how it could look.
I just did it a couple of hours ago in Windows 11 and it worked like a charm.
Cheers!!
![image](https://user-images.githubusercontent.com/86191586/126217167-f416f155-b693-41ce-9b12-001d202e105c.png)

**Comment by OwnerLink** [comment]
![image](https://user-images.githubusercontent.com/86191586/126217167-f416f155-b693-41ce-9b12-001d202e105c.png)

Unfortunately the color of the border around the window remains unchanged.

**Comment by despepas** [comment]
Can you tell me the exact steps that you followed?

**Comment by Void48** [comment]
Now with Windows 11 you can just use this: https://github.com/minusium/MicaForEveryone 👍🏻 
![image](https://user-images.githubusercontent.com/85196642/153116847-31d64969-1d69-4e40-a6da-6e38a020cbd5.png)

**Comment by milindgoel15** [comment]
Ah thanks

**Comment by maboroshin** [comment]
Summary: Darken Title bar

* Method 1. Change "Title bars and window borders" on Windows 10 **Color Setting** https://github.com/maboroshin/qBittorrentDarktheme/issues/19#issuecomment-752341401
* Method 2. Use the **Registry key** on windows 10 (But this report used Windows 11, and successful) https://github.com/maboroshin/qBittorrentDarktheme/issues/19#issuecomment-882806336
* Method 3. Use the **MicaForEveryone** on Windows 11 only https://github.com/maboroshin/qBittorrentDarktheme/issues/19#issuecomment-1033252496

**Comment by Super-Shadow** [comment]
> ![image](https://user-images.githubusercontent.com/86191586/126217167-f416f155-b693-41ce-9b12-001d202e105c.png)
> 
> Unfortunately the color of the border around the window remains unchanged.

You can change the colour border by navigating to Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Accent and changing "AccentColorMenu" to the colour you like.
